### PR TITLE
Vanilla 2.6 compatibility

### PR DESCRIPTION
**Pull request by R-J**
Make sanmyaku work with Vanilla 2.6 by:
1. changing the way custom Smarty functions are added
2. changing the way Smarty accesses controller data
3. rename the locale file

### CODE REVIEW

**Comment by valeryan** [comment]
@R-J Thanks for the MR. This looks good but I have no way of fully testing it. I will have to just take your word that it works. However, I typically build the application for a release and include a full built copy. That will not be possible with this release as I don't have the time to sort through why we can't load all the dependencies and get it to build. 

On a side note, we are looking for a maintainer who wants to make this theme their own and give it new life.

**Comment by R-J** [comment]
@valeryan I have stared this repo and therefore I saw that you are searching for a maintainer. Although I'm capable of easing out problems which come up based on Vanilla version incompatibilities, I'm doomed to fail if there are any css/js problems.
The beauty of this theme lies in the built process and how elegantly the css framework is interwoven and I really have no experience with such tools. When there is a css or js problem, I will be lost.
Therefore I do not think that I would be a good maintainer for that project.

If you allow me to do so, I can upload a new version with built resources to Vanillas addon repo. Before I do so, I would like to get feedback from @PCTipsGR who invested a lot of energy to draw attention to your project so that gets revived. If he tests the theme and finds no compatibility issues, I would upload it.

**Comment by PCTipsGR** [comment]
Thank you.

It still crashes my forum @R-J, and I have no idea on why this is caused (I made sure I downloaded latest release from the releases section).

I am running Vanilla 2.6.3 and I tested it on https://forum.ifreenet.host and https://www.mofh.ooo

**Comment by R-J** [comment]
I can open https://www.mofh.ooo/ and I see the sanmyaku theme and do not have any issues.

**Comment by PCTipsGR** [comment]
Strange.

Then it must be a preview issue, because when I had it on preview mode I got that error, with my cache cleared of course.

Anyway, thanks. The theme is working great.
I don't know if showing Vanilla logo instead of the one I chose is considered an issue to be fixed right now, but it would be nice if it could happen.

**Comment by R-J** [comment]
I do not see a reason why it should be shown in the header: I would expect to see your logo there. There is an additional Vanilla logo in the footer which is "hard coded" with css and that wouldn't change by any dashboard settings.

But to inspect further on that, you should create a new issue.

**Pull request merged**
